# The Module Name is used as prefix for all contained resources.
Module: My.VideoIndexer

# The Module Version is shown in the CloudFormation stack and Lambda function descriptions.
Version: 1.0-DEV

# The Module Description is shown in the AWS CloudFormation console with the version number.
Description: Indexes videos by extracting audio, transcribing it and indexing the results into ElasticSearch.

# The Items section defines values and resources for the module.
Items:

  - Parameter: VideoBucket
    Description: S3 Bucket for uploading videos
    Section: VideoIndexer Settings
    Label: Video Source Bucket
    Type: AWS::S3::Bucket
    Allow: Full
    Default: ""
    Properties: { }

  - Parameter: ExtractedAudioBucket
    Description: S3 Bucket for storing the extracted audio files
    Section: VideoIndexer Settings
    Label: Extracted Audio Bucket
    Scope: ExtractAudio
    Type: AWS::S3::Bucket
    Allow: ReadWrite
    Default: ""
    Properties: { }

  - Function: ExtractAudio
    Description: Function to extract audio from videos
    Memory: 1024
    Timeout: 300
    Properties:
      Layers:
        - !Ref FFmpeg::Layer
    Sources:
      - S3: VideoBucket

  - Group: FFmpeg
    Description: Create Lambda layer with FFmpeg binary
    Items:

      - Resource: Layer
        Type: AWS::Lambda::LayerVersion
        Properties:
          LicenseInfo: GPL-3.0-only
          Content:
            S3Bucket: !Ref DeploymentBucketName
            S3Key: !Ref FFmpeg::FFmpegPackage

      - Package: FFmpegPackage
        Files: Assets/FFmpeg-Layer/